#!/usr/bin/env bash -e
#
# FFmpeg
# https://git.ffmpeg.org/ffmpeg.git
#
cd "$(dirname "$0")"
set -a; . .env; set +a

pkgname="ffmpeg"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/ffmpeg"

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --arch="$(uname -m)" \
  --cpu=host \
  --cc=clang \
  --enable-shared \
  --enable-lto=thin \
  --enable-gpl \
  --enable-audiotoolbox \
  --enable-version3 \
  --enable-nonfree \
  --enable-lcms2 \
  --enable-libaom \
  --enable-libass \
  --enable-libbluray \
  --enable-libbs2b \
  --enable-libdav1d \
  --enable-libdvdnav \
  --enable-libdvdread \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-libharfbuzz \
  --enable-libjxl \
  --enable-libopus \
  --enable-libplacebo \
  --enable-libshaderc \
  --enable-libsvtav1 \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libxml2 \
  --enable-vulkan \
  --disable-debug \
  --disable-doc \
  --disable-indev=jack \
  --disable-libxcb \
  --disable-libjack \
  --disable-libtesseract \
  --disable-sdl2 \
  --disable-static \
  --disable-xlib \
  "$@"

make -j4

rm -rf "${pkgdir}"

make install
rm -rf "${pkgdir}"/share
stow -Rd "${STOWDIR}" "${pkgname}"
