#!/usr/bin/env bash -e
#
# FFmpeg
# https://git.ffmpeg.org/ffmpeg.git
#
cd "$(dirname "$0")"
set -a; source build.env; set +a

pkgname="ffmpeg"
pkgdir="${STOWDIR}/${pkgname}"
srcdir="src/ffmpeg"

cd "${srcdir}"

./configure \
  --prefix="${pkgdir}" \
  --arch="$(uname -m)" \
  --cpu=host \
  --cc=clang \
  --enable-shared \
  --enable-lto=thin \
  --enable-gpl \
  --enable-version3 \
  --enable-nonfree \
  --enable-lcms2 \
  --enable-libaom \
  --enable-libass \
  --enable-libbluray \
  --enable-libbs2b \
  --enable-libdav1d \
  --enable-libdvdnav \
  --enable-libdvdread \
  --enable-libfreetype \
  --enable-libfribidi \
  --enable-libharfbuzz \
  --enable-libjxl \
  --enable-libopus \
  --enable-libplacebo \
  --enable-libshaderc \
  --enable-libsvtav1 \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libxml2 \
  --disable-debug \
  --disable-doc \
  --disable-libxcb \
  --disable-sdl2 \
  --disable-static \
  --disable-xlib \
  --disable-hwaccels \
  --enable-hwaccel=av1_videotoolbox \
  --enable-hwaccel=h264_videotoolbox \
  --enable-hwaccel=hevc_videotoolbox \
  --enable-hwaccel=mpeg4_videotoolbox \
  --enable-hwaccel=prores_videotoolbox \
  --enable-hwaccel=vp9_videotoolbox \
  "$@"
    # --enable-libzmq \
  # --enable-audiotoolbox \
    # --enable-vulkan \
  #     --disable-indev=jack \
  # --disable-libjack \
  # --disable-libtesseract \
    # --enable-hwaccel=h263_videotoolbox \
    # --enable-hwaccel=mpeg1_videotoolbox \
  # --enable-hwaccel=mpeg2_videotoolbox \
make -j4

rm -rf "${pkgdir}"

make install
rm -rf "${pkgdir}"/share
stow -Rd "${STOWDIR}" "${pkgname}"

# vi:set ts=2 sw=2 et:
